server:
  port: 8081
spring:
  application:
    name: order-service

  datasource:
    url: jdbc:h2:file:C:/Users/bondar/H2test/Orders_DB
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
payment-service:
  path: http://localhost:8080/api/payment
  method: /savePayment